#! /usr/bin/env zsh

file=$1
shift

# generate STLA file for the given model (3D aspects only)
echo "model: ${file}"
./node_modules/.bin/jscad "${file}" -of stla $@

# generate STLA files for all existing configurations of the model (3D aspects only)
if [[ -d "${file}" ]]; then
  dir="${file}"
else
  dir=$(dirname "${file}")
fi
modelName=$(basename "${dir}")
configs=(${dir}/*(/N))
for config in ${configs}; do
  configName=$(basename "${config}")
  echo "model configuration: ${config}"
  ./node_modules/.bin/jscad "${file}" -of stla -o "${config}/${modelName}-${configName}.stl" --config "${config}" $@
done
