#! /usr/bin/env zsh

file=$1
shift

# generate SVG file for the given model (2D aspects only)
echo "model: ${file}"
./node_modules/.bin/jscad "${file}" -of svg $@

# generate SVG files for all existing configurations of the model (2D aspects only)
if [[ -d "${file}" ]]; then
  dir="${file}"
else
  dir=$(dirname "${file}")
fi
modelName=$(basename "${dir}")
configs=(${dir}/*(/N))
for config in ${configs}; do
  configName=$(basename "${config}")
  echo "model configuration: ${config}"
  ./node_modules/.bin/jscad "${file}" -of svg -o "${config}/${modelName}-${configName}.svg" --config "${config}" $@
done
